// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1H1tQJA6knqSqvjkFttMbK0USndNYmHo',
    appId: '1:17306734556:web:9536e5ecafdc74e4f6c919',
    messagingSenderId: '17306734556',
    projectId: 'ritoselfcheckout-3aead',
    authDomain: 'ritoselfcheckout-3aead.firebaseapp.com',
    storageBucket: 'ritoselfcheckout-3aead.appspot.com',
    measurementId: 'G-HENDMCJK5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpsxFnMWct6OIoXazDtT9w51Be6WPyeLI',
    appId: '1:17306734556:android:a5ca120659c73844f6c919',
    messagingSenderId: '17306734556',
    projectId: 'ritoselfcheckout-3aead',
    storageBucket: 'ritoselfcheckout-3aead.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBKavFU0Ajg_v6msL3SNWOC5Eerk47iJY',
    appId: '1:17306734556:ios:e74339c618f5e925f6c919',
    messagingSenderId: '17306734556',
    projectId: 'ritoselfcheckout-3aead',
    storageBucket: 'ritoselfcheckout-3aead.appspot.com',
    iosBundleId: 'com.ritoselfcheckout.ritoselfcheckout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBKavFU0Ajg_v6msL3SNWOC5Eerk47iJY',
    appId: '1:17306734556:ios:6f3d4bfdd8f9fd9ef6c919',
    messagingSenderId: '17306734556',
    projectId: 'ritoselfcheckout-3aead',
    storageBucket: 'ritoselfcheckout-3aead.appspot.com',
    iosBundleId: 'com.ritoselfcheckout.ritoselfcheckout.RunnerTests',
  );
}
